*"* components of interface ZIF_GUI_SIMPLE_TREE_EVENTS
interface ZIF_GUI_SIMPLE_TREE_EVENTS
  public .


  methods HANDLE_PROPERTY_CHANGED .
  methods HANDLE_RIGHT_CLICK .
  methods HANDLE_LEFT_CLICK_DESIGN .
  methods HANDLE_MOVE_CONTROL .
  methods HANDLE_SIZE_CONTROL .
  methods HANDLE_LEFT_CLICK_RUN .
  methods HANDLE_CONTEXT_MENU_REQUEST .
  methods HANDLE_CONTEXT_MENU_SELECT .
  methods HANDLE_EXPAND_NO_CHILDREN .
  methods HANDLE_NODE_CONTEXT_MENU_REQ .
  methods HANDLE_NODE_CONTEXT_MENU_SEL .
  methods HANDLE_NODE_DOUBLE_CLICK .
  methods HANDLE_NODE_KEYPRESS .
  methods HANDLE_ON_DROP .
  methods HANDLE_ON_DROP_GET_FLAVOR .
  methods HANDLE_SELECTION_CHANGED .
  methods HANDLE_ON_DRAG .
  methods HANDLE_ON_DRAG_MULTIPLE .
  methods HANDLE_ON_DROP_COMPLETE .
  methods HANDLE_ON_DROP_COMPLETE_MULT .
endinterface.
