*&---------------------------------------------------------------------*
*&  Include           MZBOOK_DEMOO01
*&---------------------------------------------------------------------*

*&SPWIZARD: OUTPUT MODULE FOR TS 'TC_DEMO'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE TC_DEMO_ACTIVE_TAB_SET OUTPUT.
  TC_DEMO-ACTIVETAB = G_TC_DEMO-PRESSED_TAB.
  CASE G_TC_DEMO-PRESSED_TAB.
    WHEN C_TC_DEMO-TAB1.
      G_TC_DEMO-SUBSCREEN = '0501'.
    WHEN C_TC_DEMO-TAB2.
      G_TC_DEMO-SUBSCREEN = '0502'.
    WHEN C_TC_DEMO-TAB3.
      G_TC_DEMO-SUBSCREEN = '0503'.
    WHEN C_TC_DEMO-TAB4.
      G_TC_DEMO-SUBSCREEN = '0504'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TC_VBAK'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TC_VBAK_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE GT_VBAK LINES TC_VBAK-lines.
ENDMODULE.
